### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by atul221282** [ymassad/AOPExamples#1]
Hi ,

I read your blog and ended here on this repo which looks good but just got one question

Does this repo support .net core?

Regards

**Comment by ymassad** [comment]
Hi,

I created this repository just as an example for the article. It is not meant to be used in production as is.

I am not sure if it can be ported to support .NET core. It has a dependency on Castle DynamicProxy and I don't know if this package supports .NET core.

You can try to port it and see if it works.
